export const justifications = [
  "No justification field is present",
  "Unknown justification",
  "REASON_UNSPECIFIED",
  "CUSTOMER_INITIATED_SUPPORT",
  "GOOGLE_INITIATED_SERVICE",
  "THIRD_PARTY_DATA_REQUEST",
  "GOOGLE_INITIATED_REVIEW",
  "CUSTOMER_INITIATED_ACCESS",
  "GOOGLE_INITIATED_SYSTEM_OPERATION",
  "REASON_NOT_EXPECTED",
  "MODIFIED_CUSTOMER_INITIATED_ACCESS",
  "MODIFIED_GOOGLE_INITIATED_SYSTEM_OPERATION",
  "GOOGLE_RESPONSE_TO_PRODUCTION_ALERT",
  "CUSTOMER_AUTHORIZED_WORKFLOW_SERVICING",
];

export const cryptospacePermissions = {
  Create: "CREATE_KEY",
  Destroy: "DESTROY_KEY",
  Wrap: "WRAP",
  Unwrap: "UNWRAP",
  "Get Public": "GET_PUBLIC_KEY",
  Sign: "ASYMMETRIC_SIGN",
  Info: "GET_INFO",
};

// todo: Human readable strings
export const keyAlgorithms = [
  "ALGORITHM_RSA_SIGN_PSS_2048_SHA256",
  "ALGORITHM_RSA_SIGN_PSS_3072_SHA256",
  "ALGORITHM_RSA_SIGN_PSS_4096_SHA256",
  "ALGORITHM_RSA_SIGN_PSS_4096_SHA512",
  "ALGORITHM_RSA_SIGN_PKCS1_2048_SHA256",
  "ALGORITHM_RSA_SIGN_PKCS1_3072_SHA256",
  "ALGORITHM_RSA_SIGN_PKCS1_4096_SHA256",
  "ALGORITHM_RSA_SIGN_PKCS1_4096_SHA512",
  "ALGORITHM_EC_SIGN_P256_SHA256",
  "ALGORITHM_EC_SIGN_P384_SHA384",
  "ALGORITHM_EXTERNAL_SYMMETRIC_ENCRYPTION",
];
