openapi: 3.0.0

info:
  version: "1.0.2"
  title: 'Features'
  description: |
    ***
    ### Authentication Methods
    ***
    + HTTP Bearer token (JSON web token)
    + XSRF Session token
    ***
    ### Important Notes
    ***
    + 

security:
  - bearerToken: []
  - session: []
    XSRF-TOKEN: []

paths:
  /features:
    get:
      tags:
        - Features
      summary: 'Retrieve feature settings.'
      description: |
        ***
        ### Requirements
        ***
        + **Features**
          + 
        + **Host API Commands**
          + SETT, FN features
        + **Permissions**
          +
        ***
        ### Additional Notes
        ***
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveFeatureList'
              examples:
                'Retrieve list of Features':
                  $ref: '#/components/examples/RetrieveFeatureList'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '401':
          $ref: '#/components/responses/401-Unauthorized'
        '403':
          $ref: '#/components/responses/403-Forbidden'
        '404':
          $ref: '#/components/responses/404-NotFound'
        default:
          $ref: '#/components/responses/500-InternalError'

  '/feature-request':
    get:
      tags:
        - Feature Requests
      summary: 'Download feature request file.'
      description: |
        ***
        ### Requirements
        ***
        + **Features**
          + 
        + **Host API Commands**
          + SETT, FN feature_request
        + **Permissions**
          +
        ***
        ### Additional Notes
        ***
      responses:
        '200':
          description: OK
          content:
            application/*:
              schema:
                $ref: '#/components/schemas/DownloadFeatureRequest'
              examples:
                'Download Feature Request':
                  $ref: '#/components/examples/DownloadFeatureRequest'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '401':
          $ref: '#/components/responses/401-Unauthorized'
        '403':
          $ref: '#/components/responses/403-Forbidden'
        '404':
          $ref: '#/components/responses/404-NotFound'
        default:
          $ref: '#/components/responses/500-InternalError'

  '/feature-request/upload':
    put:
      tags:
        - Feature Requests
      summary: 'Upload feature request file.'
      description: |
        ***
        ### Requirements
        ***
        + **Features**
          + 
        + **Host API Commands**
          + SETT, FN feature_request
        + **Permissions**
          +
        ***
        ### Additional Notes
        ***
        + File uploads should be submitted via a multi-part/form request
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UploadFeatureRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UploadFeatureRequestResponse'
              examples:
                'success':
                  $ref: '#/components/examples/UploadFeatureRequestResponse'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '401':
          $ref: '#/components/responses/401-Unauthorized'
        '403':
          $ref: '#/components/responses/403-Forbidden'
        '404':
          $ref: '#/components/responses/404-NotFound'
        default:
          $ref: '#/components/responses/500-InternalError'

components:
  securitySchemes:
    bearerToken:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/securitySchemes/bearerToken'
    session:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/securitySchemes/session'
    XSRF-TOKEN:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/securitySchemes/XSRF-TOKEN'

  schemas:
    RetrieveFeatureList:
      allOf:
        - $ref: '#/components/schemas/ResponseBase'
        - type: object
          properties:
            response:
              type: object
              properties:
                application:
                  $ref: '#/components/schemas/FeatureListObject'
                firmware:
                  $ref: '#/components/schemas/FeatureListObject'
                virtual:
                  $ref: '#/components/schemas/FeatureListObject'
              required:
                - application
                - firmware
                - virtual
    DownloadFeatureRequest:
      allOf:
        - $ref: '#/components/schemas/ResponseBase'
        - type: object
          properties:
            response:
              type: object
              properties:
                featureRequest:
                  type: string
                  format: binary
                  description: 'Feature Request file to be downloaded.'
    UploadFeatureRequest:
      type: object
      properties:
        featureRequest:
          type: string
          format: binary
          description: 'Feature Request file to be uploaded.'
    UploadFeatureRequestResponse:
      allOf:
        - $ref: '#/components/schemas/ResponseBase'
        - type: object
          properties:
            response:
              type: object
              properties:
                jobId:
                  type: string
                  format: UUID
                  description: 'Unique ID of newly created job.'
              required:
                - jobId
    FeatureListObject:
      # This schema is intended to return a dynamic object with key/value pairs
      # e.g. '{ key : "value", key : "value", key : "value" }'
      type: object
      additionalProperties:
        type: string
    ResponseBase:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/schemas/ResponseBase'

  responses:
    200-OK:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/200-OK'
    201-Created:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/201-Created'
    400-BadRequest:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/400-BadRequest'
    401-Unauthorized:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/401-Unauthorized'
    403-Forbidden:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/403-Forbidden'
    404-NotFound:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/404-NotFound'
    500-InternalError:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/500-InternalError'

  examples:
    RetrieveFeatureList:
      value:
        status: 'Success'
        message: ''
        response:
          application:
            AES: true
            NTP: true
            ExternalApp: true
            FTP: true
            RemoteDesktop: true
          firmware:
            ADMINPORT: true
            CLEARKEYLOAD: 2
            ECC: true
            GPMODE: true
          virtual:
            SPEED: 1000000
            RSA: true
            ECC: true
            PKCS11: true
    DownloadFeatureRequest:
      value:
        status: 'Success'
        message: ''
        response:
          featureRequest: '<file_contents>'
    UploadFeatureRequestResponse:
      value:
        status: 'Success'
        message: ''
        response:
          jobId: '12345ABCD'
