openapi: 3.0.0

info:
  version: "1.0.2"
  title: 'Jobs'
  description: |
    ***
    ### Authentication Methods
    ***
    + HTTP Bearer token (JSON web token)
    + XSRF Session token
    ***
    ### Important Notes
    ***
    + 

security:
  - bearerToken: []
  - session: []
    XSRF-TOKEN: []

paths:
  /jobs:
    get:
      tags:
        - Jobs
      summary: 'Retrieve a list of current jobs.'
      description: |
        ***
        ### Requirements
        ***
        + **Features**
          + 
        + **Host API Commands**
          + 
        + **Permissions**
          +
        ***
        ### Additional Notes
        ***
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RetrieveJobList'
              examples:
                'Retrieve list of Jobs':
                  $ref: '#/components/examples/RetrieveJobList'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '401':
          $ref: '#/components/responses/401-Unauthorized'
        '403':
          $ref: '#/components/responses/403-Forbidden'
        '404':
          $ref: '#/components/responses/404-NotFound'
        default:
          $ref: '#/components/responses/500-InternalError'

components:
  securitySchemes:
    bearerToken:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/securitySchemes/bearerToken'
    session:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/securitySchemes/session'
    XSRF-TOKEN:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/securitySchemes/XSRF-TOKEN'

  schemas:
    RetrieveJobList:
      allOf:
        - $ref: '#/components/schemas/ResponseBase'
        - type: object
          properties:
            response:
              type: object
              properties:
                totalJobs:
                  type: integer
                  minimum: 0
                  description: 'Total number of active jobs.'
                jobs:
                  type: array
                  items:
                    allOf:
                      - $ref: '#/components/schemas/Job'
                      - required:
                        - id
                        - status
                        - summary
                        - created
                        - started
                  description: 'List of active jobs.'
              required:
                - totalJobs
                - jobs
    Job:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: 'Unique job ID.'
        status:
          type: string
          description: 'Job status.'
        summary:
          type: string
          description: 'Summary of job.'
        created:
          type: string
          format: datetime
          description: 'Date/time the job was created.'
        started:
          type: string
          format: datetime
          description: 'Date/time the job started.'
    ResponseBase:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/schemas/ResponseBase'

  responses:
    200-OK:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/200-OK'
    201-Created:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/201-Created'
    400-BadRequest:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/400-BadRequest'
    401-Unauthorized:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/401-Unauthorized'
    403-Forbidden:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/403-Forbidden'
    404-NotFound:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/404-NotFound'
    500-InternalError:
      $ref: 'https://api.swaggerhub.com/domains/Futurex/common/1.0.0#/components/responses/500-InternalError'

  examples:
    RetrieveJobList:
      value:
        status: 'success'
        message: ''
        response:
          totalJobs: 3
          jobs:
            - id: '100'
              status: 'Complete'
              summary: 'Job #1'
              created: '2020-01-01T12:00:00Z'
              started: '2020-01-01T12:00:05Z'
            - id: '22329'
              status: 'Running'
              summary: 'Job #2'
              created: '2020-01-01T12:10:32Z'
              started: '2020-01-01T12:10:32Z'
            - id: '22330'
              status: 'Queued'
              summary: 'Job #3'
              created: '2020-01-01T12:10:32Z'
              started: ''
